### ISSUE TITLE
Just so you know, it thinks that 127W is 12.7W

### ISSUE THREAD

**Issue by ilikenwf** [ctlcltd/e2-sat-editor#21]
### Describe the bug

There's a parse issue, when I connect and download everything from my e2 box, it sees my 127W channels and marks them as belonging to 12.7W.

### Steps to reproduce

1. 
2. 
3. 
...

### Software version

1.4

### Download medium

GitHub Releases page

### Platform running

I don't know

### Architecture running

I don't know

**Comment by ctlcltd** [comment]
Sorry I can not find an authentic channel list for 127W on the internet, if you can upload an unedited list for 127W, taken from the decoder, it would help.

I did some testing, the value read from satellites.xml is correct, “127.0W C-band Galaxy 37/Horizons 4” shows 127.1W as expected. Also in edit is correct.

As far as I know, the orbital position value could be multiplied with West. This situation is not currently considered. Above 180 deg should be = 3600 - position, but would not be 12.7. Still to be investigated.

Thanks

**Comment by ilikenwf** [comment]
I'm using the satellites.xml from https://sat-forum.net/viewtopic.php?t=131&sid=a06764ad9f180a91970f14ba9b6046a2&start=140 because it's so fresh most of the time, scraped from lyngsat.

**Comment by ilikenwf** [comment]
...from what I can tell, other than maybe 5-7 channels extra, it's accurate.

**Comment by ctlcltd** [comment]
Thanks for the suggestion!
I would need a services list directly from a decoder, it would be more accurate.

**Comment by ilikenwf** [comment]
My e2 box should be able to output that for you to xml, right?

**Comment by ctlcltd** [comment]
Yes, saving from the software or taking the files directly from the decoder and zipping them.
The services file is "lamedb", or "lamedb5", or "services" (older Enigma), or "services.xml" (Neutrino).
Many decoders also export from a USB stick.

**Comment by ilikenwf** [comment]
[lamedb.zip](https://github.com/ctlcltd/e2-sat-editor/files/15223670/lamedb.zip)

Forgot I already had a copy from playing with the editor, though this should only have the adult lock applied to the two xxx channels...I don't want those personally.

**Comment by ctlcltd** [comment]
Thank you so much, I solved the mistake.
I limited the value to 4 digits, thus it does not parse the minus sign with negative 4 digit values.
The fix will take effect on the next release.

**Comment by ilikenwf** [comment]
Ah, very cool! Thanks for the great editor.
