### ISSUE TITLE
donate per bitcoin 

### ISSUE THREAD

**Issue by skyerjoe** [ctlcltd/e2-sat-editor#28]
hello 

is it possible to donate over bitcoin ?

best regards

**Comment by ctlcltd** [comment]
No at this moment, directly.
Paypal donate button is used for convenience.

- To donate with cryptocurrencies use an exchange (trusted) platform and cash out crypto to money (for example USD, EUR, AUD), then donate through PayPal using an account or cards.

It is easy to convert cryptos.

(A crypto wallet for micro-donations maybe for near future. Need dedicated exchange account and wallet, here we have strict anti-money laundering rules)

**Comment by skyerjoe** [comment]
ok

**Comment by skyerjoe** [comment]
I still donated , cause u have the only tool which is able to handle large db files. 

no other tools which i tried could handle this 

regards

**Comment by ctlcltd** [comment]
very glad to hear that

I focused on access/reading performance, tried large files also, certainly improvable.
The software can still improve lot and lot... I do not have many resources to invest in it.
It would be wonderful to have more resources and public feedback.
Latest version 1.8 is the most stable possible, to get 2.0 will take more effort...

I confirm, I received a donation on September 29, 2024, very nice, thank you
